"""Study module ORM models: projects, units, sessions, exams, messages, exercises."""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base
from app.db_types import CreatedAtMixin, TimestampMixin, UUIDPKMixin


# ---- Project statuses ----------------------------------------------------
# ``planning``  — plan generation is pending or in flight; no units yet.
# ``active``    — plan exists; student is working through units.
# ``completed`` — final exam passed; project is eligible for archiving.
# ``archived``  — filed away; still readable, not shown in the active tab.
ProjectStatus = str  # 'planning' | 'active' | 'completed' | 'archived'


class StudyProject(UUIDPKMixin, TimestampMixin, Base):
    __tablename__ = "study_projects"

    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    topics: Mapped[list[str]] = mapped_column(
        ARRAY(String), nullable=False, default=list, server_default="{}"
    )
    goal: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Raw "I want to learn..." description the student entered when
    # creating the topic. The planner LLM reads this verbatim to emit
    # a unit plan; we keep it around so we can regenerate if the first
    # plan turns out to be off-base.
    learning_request: Mapped[str | None] = mapped_column(Text, nullable=True)
    # AI-inferred difficulty tag surfaced in the UI card (beginner /
    # intermediate / advanced / mixed). Free-form string — not enforced
    # at the DB layer because the planner may decide "intro-to-advanced"
    # or similar.
    difficulty: Mapped[str | None] = mapped_column(String(16), nullable=True)
    # Student's self-reported starting level, collected in the New Study
    # wizard. One of ``beginner`` / ``some_exposure`` / ``refresher``, or
    # None if they skipped the field. The planner uses this to pace the
    # plan (beginners on advanced topics like CCNA get explicit
    # foundations units at the front); the unit tutor uses it as a
    # default register until the Unit 1 diagnostic confirms or corrects
    # it.
    current_level: Mapped[str | None] = mapped_column(String(24), nullable=True)
    # Whether the Unit 1 forced diagnostic has run on this project yet.
    # Flipped true by the tutor emitting ``calibration_complete`` or
    # ``insert_prerequisites`` with ``mark_calibrated=true``. Reset to
    # false when the plan is regenerated.
    calibrated: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )
    # How calibration flipped on for this project. One of ``skipped``
    # (student clicked "Skip diagnostic"), ``tutor_set`` (tutor emitted
    # ``set_calibrated`` at the end of a clean warm-up), or
    # ``tutor_insert`` (tutor emitted ``insert_prerequisites`` and the
    # handler auto-calibrated). NULL until the flag first flips. Never
    # overwritten once set so we can honestly report whether the
    # student took the warm-up seriously.
    calibration_source: Mapped[str | None] = mapped_column(String(16), nullable=True)
    # One-shot timestamp for the ``calibration_warning`` SSE event.
    # NULL means "the honesty nudge has not fired yet"; any value
    # means "already shown, don't show again".
    calibration_warning_sent_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    model_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    planning_provider_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("model_providers.id", ondelete="SET NULL"),
        nullable=True,
    )
    planning_error: Mapped[str | None] = mapped_column(Text, nullable=True)

    status: Mapped[str] = mapped_column(
        String(16), nullable=False, default="planning", server_default="active"
    )
    archived_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    def __repr__(self) -> str:
        return f"<StudyProject id={self.id} title={self.title!r} status={self.status}>"


class StudyUnit(UUIDPKMixin, TimestampMixin, Base):
    """One ordered slice of the learning plan for a ``StudyProject``.

    Units are generated by the AI planner right after a project is
    created and remain mostly static after that — only ``status``,
    ``mastery_score``, ``completed_at`` and ``last_studied_at`` flip as
    the student progresses. ``exam_focus`` is populated when a failed
    exam surfaces specific weaknesses for this unit; the unit tutor
    prepends it to its next system prompt so follow-up study targets
    exactly what the exam found missing.
    """

    __tablename__ = "study_units"

    project_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("study_projects.id", ondelete="CASCADE"),
        nullable=False,
    )
    order_index: Mapped[int] = mapped_column(Integer, nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="", server_default="")
    learning_objectives: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, default=list, server_default="'[]'::jsonb"
    )

    # 'not_started' | 'in_progress' | 'completed'
    status: Mapped[str] = mapped_column(
        String(16), nullable=False, default="not_started", server_default="not_started"
    )
    mastery_score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    mastery_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    exam_focus: Mapped[str | None] = mapped_column(Text, nullable=True)

    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_studied_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    session_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey(
            "study_sessions.id",
            ondelete="SET NULL",
            use_alter=True,
            name="fk_study_units_session_id",
        ),
        nullable=True,
    )

    # True for units the tutor inserted mid-plan via
    # ``insert_prerequisites`` (either proactively during a unit session
    # or as the outcome of the Unit 1 calibration diagnostic). Surfaced
    # in the UI with a subtle "added by tutor" label so the student can
    # distinguish original plan units from fill-in foundations.
    inserted_as_prereq: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )
    # Free-form reason the tutor provided when emitting
    # ``insert_prerequisites``. Shown verbatim in the "Added by tutor"
    # banner on the topic page so the student understands why the plan
    # was modified without re-reading chat.
    prereq_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Shared UUID for every unit inserted by the same tutor reply, so
    # the UI can group them into a single dismissible banner keyed in
    # localStorage.
    prereq_batch_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )

    def __repr__(self) -> str:
        return (
            f"<StudyUnit id={self.id} #{self.order_index} {self.title!r} "
            f"status={self.status}>"
        )


class StudyExam(UUIDPKMixin, TimestampMixin, Base):
    """One attempt at the final exam for a project.

    A project can have multiple ``StudyExam`` rows — one per attempt.
    Only one row at a time can be in ``in_progress``; the rest are
    ``pending``/``passed``/``failed`` terminals. Failing an exam flips
    the project back into ``active`` state and unlocks the listed
    ``weak_unit_ids`` for targeted re-study.
    """

    __tablename__ = "study_exams"

    project_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("study_projects.id", ondelete="CASCADE"), nullable=False
    )
    session_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey(
            "study_sessions.id",
            ondelete="SET NULL",
            use_alter=True,
            name="fk_study_exams_session_id",
        ),
        nullable=True,
    )

    attempt_number: Mapped[int] = mapped_column(Integer, nullable=False, default=1, server_default="1")
    # 'pending' | 'in_progress' | 'passed' | 'failed'
    status: Mapped[str] = mapped_column(
        String(16), nullable=False, default="pending", server_default="pending"
    )
    time_limit_seconds: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1200, server_default="1200"
    )

    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    passed: Mapped[bool | None] = mapped_column(Boolean, nullable=True)

    weak_unit_ids: Mapped[list[uuid.UUID] | None] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=True
    )
    strong_unit_ids: Mapped[list[uuid.UUID] | None] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=True
    )
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Per-unit grader notes keyed by stringified unit id —
    # ``{unit_id: "1-2 sentence note"}``. Populated by the grader LLM
    # when it emits the ``grade`` exam action; surfaced in the topic
    # page "Exam breakdown" panel alongside the weak/strong lists.
    unit_notes: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    def __repr__(self) -> str:
        return f"<StudyExam id={self.id} status={self.status} score={self.score}>"


class StudySession(UUIDPKMixin, TimestampMixin, Base):
    __tablename__ = "study_sessions"

    project_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("study_projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    # Full Excalidraw scene JSON, debounced auto-save every ~30s.
    excalidraw_snapshot: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    # Discriminator: ``unit`` for unit-tutor sessions, ``exam`` for a
    # final-exam session, ``legacy`` for free-form sessions created
    # before the Units feature landed.
    kind: Mapped[str] = mapped_column(
        String(16), nullable=False, default="unit", server_default="legacy"
    )
    unit_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("study_units.id", ondelete="SET NULL"), nullable=True
    )
    exam_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("study_exams.id", ondelete="SET NULL"), nullable=True
    )

    def __repr__(self) -> str:
        return f"<StudySession id={self.id} kind={self.kind} project_id={self.project_id}>"


class WhiteboardExercise(UUIDPKMixin, CreatedAtMixin, Base):
    __tablename__ = "whiteboard_exercises"

    session_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("study_sessions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    # Circular reference with study_messages — broken during DDL via use_alter.
    message_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey(
            "study_messages.id",
            ondelete="SET NULL",
            use_alter=True,
            name="fk_whiteboard_exercises_message_id",
        ),
        nullable=True,
    )

    title: Mapped[str | None] = mapped_column(String(255), nullable=True)
    html: Mapped[str] = mapped_column(Text, nullable=False)

    # 'active' | 'submitted' | 'reviewed'
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, default="active", server_default="active"
    )

    answer_payload: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    excalidraw_snap: Mapped[str | None] = mapped_column(Text, nullable=True)  # base64 PNG
    ai_feedback: Mapped[str | None] = mapped_column(Text, nullable=True)

    submitted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    def __repr__(self) -> str:
        return f"<WhiteboardExercise id={self.id} status={self.status}>"


class StudyMessage(UUIDPKMixin, CreatedAtMixin, Base):
    __tablename__ = "study_messages"

    session_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("study_sessions.id", ondelete="CASCADE"), nullable=False, index=True
    )

    role: Mapped[str] = mapped_column(String(32), nullable=False)
    # Chat text with `<whiteboard_action>` blocks stripped.
    content: Mapped[str] = mapped_column(Text, nullable=False, default="", server_default="")

    exercise_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey(
            "whiteboard_exercises.id",
            ondelete="SET NULL",
            use_alter=True,
            name="fk_study_messages_exercise_id",
        ),
        nullable=True,
    )

    def __repr__(self) -> str:
        return f"<StudyMessage id={self.id} role={self.role}>"
